# Endpoint: https://integbio.jp/togosite/sparql
# Description: Get regulation pairs

PREFIX cao: <http://chip-atlas.org/ontology/>

SELECT ?PutativeRegulation ?tg_tf ?tg_target
FROM <http://rdf.integbio.jp/dataset/togosite/chip_atlas>
WHERE {
    ?PutativeRegulation a cao:PutativeRegulation ;
        cao:hasTF ?tg_tf ;
        cao:hasTargetGene ?tg_target .
}
LIMIT 100
