# Endpoint: http://sparql.med2rdf.org/sparql
# Description: Obrain drug-gene interaction pairs from DGIdb

PREFIX dgio: <http://purl.jp/bio/10/dgidb/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?interaction_type ?drug_name ?chembl_molecule ?gene_name ?alternative_name ?ncbi_gene ?publication
FROM <http://med2rdf.org/graph/dgidb>
WHERE {
    ?DGIdbInteraction a dgio:Interaction ;
        dgio:drug / rdfs:label ?drug_name ;
        dgio:drug / rdfs:seeAlso ?chembl_molecule ;
        dgio:gene / rdfs:label ?gene_name ;
        dgio:gene / skos:altLabel ?alternative_name ;
        dgio:gene / rdfs:seeAlso ?ncbi_gene .
    OPTIONAL {
        ?DGIdbInteraction dgio:interactionType ?interaction_type .
    }
    OPTIONAL {
        ?DGIdbInteraction rdfs:seeAlso ?publication .
    }
}
LIMIT 100
