# Endpoint: http://sparql.med2rdf.org/sparql
# Description: Obrain variant annotations from ExAC
# Parameter: identifier: (example: 4-100197800-C-T)

PREFIX exo: <http://purl.jp/bio/10/exac/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT ?identifier ?allele_count ?allele_num ?num_of_homozygotes ?allele_frequency ?consequence ?hgvs ?annotation_consequence ?annotation_gene ?annotation_protein ?annotation_transcript ?annotation_gene_symbol ?annotation_agvsc ?annotation_hgvsp ?annotation_hgnc
WHERE {
    VALUES ?identifier { "4-100197800-C-T" }
    ?ExACValiation a exo:Variant ;
        dct:identifier ?identifier ;
        exo:alleleCount ?allele_count ;
        exo:alleleNum ?allele_num ;
        exo:numOfHomozygotes ?num_of_homozygotes ;
        exo:alleleFrequency ?allele_frequency ;
        exo:consequence ?consequence ;
        exo:hgvs ?hgvs ;
        exo:annotation / exo:consequence ?annotation_consequence ;
        exo:annotation / exo:ensemblGene ?annotation_gene ;
        exo:annotation / exo:ensemblProtein ?annotation_protein ;
        exo:annotation / exo:ensemblTranscript ?annotation_transcript ;
        exo:annotation / exo:geneSymbol ?annotation_gene_symbol ;
        exo:annotation / exo:hgvsc ?annotation_agvsc ;
        exo:annotation / exo:hgvsp ?annotation_hgvsp ;
        exo:annotation / so:variant_of ?annotation_hgnc .
}
LIMIT 100
