# Endpoint: https://rdfportal.org/primary/sparql
# Description: SPARQL description.


SELECT
FROM <http://jcggdb.jp/rdf/diseases/ggdonto>
FROM <http://jcggdb.jp/rdf/diseases/ggdonto-schema.rdf>
WHERE {
}
LIMIT 100
