# Endpoint: http://sparql.med2rdf.org/sparql
# Description: Obrain human chromosomes from the HCO ontology

PREFIX hco: <http://identifiers.org/hco/>

SELECT ?Chromosome ?build ?length ?insdc ?refseq ?ucsc ?ensembl
WHERE {
    ?Chromosome hco:build ?build ;
        hco:length ?length ;
        hco:insdc ?insdc ;
        hco:refseq ?refseq ;
        hco:ucsc ?ucsc ;
        hco:ensembl ?ensembl .
}
LIMIT 100
