# Endpoint: http://sparql.med2rdf.org/sparql
# Description: Obrain protein-protein interaction pairs from the HiNT database

PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pint: <http://purl.jp/10/pint/>

SELECT ?data_source ?display_hame ?evidence ?name ?pair0 ?pair1 ?network_variety ?accuracy
WHERE {
    ?HiNT a bp3:MolecularInteraction ;
        bp3:dataSource ?data_source ;
        bp3:displayName ?display_hame ;
        bp3:evidence ?evidence ;
        bp3:name ?name ;
        bp3:participant / obo:BFO_0000051 ?pair0 ;
        bp3:participant / obo:BFO_0000051 ?pair1 .
    OPTIONAL {
        ?HiNT pint:networkVariety ?network_variety .
    }
    OPTIONAL {
        ?HiNT pint:accuracy ?accuracy .
    }
}
LIMIT 100
