# Endpoint: http://sparql.med2rdf.org/sparql
# Description: Obrain IF_0

PREFIX ifo: <http://med2rdf.org/ontology/ifo/>

SELECT ?package_insert
WHERE {
    ?InterviewForm a ifo:InterviewForm ;
        ifo:package_insert ?package_insert .
}
LIMIT 100
