# Endpoint: https://rdfportal.org/primary/sparql
# Description: SPARQL description.

PREFIX icgc: <http://icgc.link/>
PREFIX ivocab: <inv-http://icgc.link/vocab/>
PREFIX vocab: <http://icgc.link/vocab/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?Mutation ?effect ?detection ?project ?affected_gene ?ensembl
FROM <http://icgc.link/release_20>
WHERE {
    ?Mutation a icgc:Mutation ;
        ivocab:mutation ?effect ;
        ivocab:mutation ?detection .
    ?effect a icgc:Effect ;
        vocab:gene_affected ?affected_gene .
    ?detection a icgc:Detection ;
        vocab:project ?project .
    ?project a icgc:Project .
    ?affected_gene a icgc:Gene ;
        rdfs:seeAlso ?ensembl .
}
LIMIT 100
