# Endpoint: https://rdfportal.org/primary/sparql
# Description: SPARQL description.

PREFIX orth: <http://purl.org/net/orth#>
PREFIX mbgd: <http://purl.jp/bio/11/mbgd#>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX void: <http://rdfs.org/ns/void#>

SELECT ?Cluster ?gene ?dataset ?nucseq ?organism
FROM <http://mbgd.genome.ad.jp/rdf/resource/default>
FROM <http://mbgd.genome.ad.jp/rdf/resource/gene>
FROM <http://mbgd.genome.ad.jp/rdf/resource/organism>
FROM <http://mbgd.genome.ad.jp/rdf/resource/nucseq>
FROM <http://mbgd.genome.ad.jp/rdf/resource/xref_uniprot>
FROM <http://purl.jp/bio/11/orth>
FROM <http://purl.jp/bio/11/mbgd>
WHERE {
    VALUES ?gene__class { orth:Gene mbgd:CDS }
    VALUES ?dataset__class { void:Dataset orth:OrthologyDataset }
    VALUES ?nucseq__class { mbgd:Chromosome mbgd:Circular }
    VALUES ?organism__class { mbgd:Genome mbgd:CompleteGenome }
    ?Cluster a orth:OrthologsCluster ;
        orth:hasHomologous / mbgd:gene ?gene ;
        void:inDataset ?dataset .
    ?dataset a ?dataset__class .
    ?gene a ?gene__class ;
        mbgd:nucSeq ?nucseq ;
        mbgd:organism ?organism .
    ?nucseq a ?nucseq__class .
    ?organism a ?organism__class .
}
LIMIT 100
