# Endpoint: https://rdfportal.org/primary/sparql
# Description: Obtain taxonomy ID and preferred label of a bioresource
# Parameter: nbrc_id: (example: NBRC_00100650)
#            attribute: (example: meo:MEO_0000198)

PREFIX mccv: <http://purl.jp/bio/10/mccv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX meo: <http://purl.jp/bio/11/meo/>

SELECT ?nbrc_id ?clade ?name ?alias ?taxid ?attribute ?habitat
FROM <http://purl.jp/bio/103/nite/culture/>
WHERE {
    VALUES ?nbrc_id { "NBRC_00100650" }
    VALUES ?attribute { meo:MEO_0000198 }
    VALUES ?_b1__class { mccv:MCCV_000006 sio:SIO_001050 }
    ?Culture a mccv:MCCV_000001 ;
        dct:identifier ?nbrc_id ;
        mccv:MCCV_000038 ?clade ;
        skos:prefLabel ?name ;
        skos:altLabel ?alias ;
        mccv:MCCV_000065 ?taxid ;
        mccv:MCCV_000028 / mccv:MCCV_000072 / mccv:MCCV_000030 ?habitat ;
        mccv:MCCV_000028 [
            a ?_b1__class ;
            mccv:MCCV_000072 [
                a mccv:MCCV_000007 ;
                sio:SIO_000008 ?attribute ;
            ] ;
        ] .
}
LIMIT 100
