# Endpoint: https://rdfportal.org/primary/sparql
# Description: Get orthologs of a given RefSeq ID.
# Parameter: dataset: (example: protid:NP_563687.1)

PREFIX orth: <http://purl.jp/bio/11/orth#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX protid: <http://identifiers.org/ncbiprotein/>

SELECT ?protid
FROM <http://pgdbj.jp/od/>
FROM <http://purl.jp/bio/11/orth#>
WHERE {
    VALUES ?Group__class { orth:OrthologGroup orth:ParalogGroup }
    OPTIONAL {
        ?Group a ?Group__class ;
            orth:member / rdfs:seeAlso ?protid .
    }
}
LIMIT 100
